services:
  api:
    container_name: api
    restart: always
    build:
      context: api
    volumes:
      - ./api:/api
      - /api/node_modules
    expose:
      - 3000
    ports:
      - 3000:3000
    command: yarn dev

  web:
    container_name: web
    restart: always
    depends_on:
      - api
    build:
      context: web
    volumes:
      - ./web:/web
    ports:
      - 8080:80
